/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An airtable field with its options.
 */
export interface Field {
  id: string;
  type?:
    | "singleLineText"
    | "multilineText"
    | "richText"
    | "number"
    | "percent"
    | "currency"
    | "rating"
    | "date"
    | "dateTime"
    | "duration"
    | "createdTime"
    | "lastModifiedTime"
    | "singleSelect"
    | "multipleSelect"
    | "singleCollaborator"
    | "multipleCollaborators"
    | "multipleAttachments"
    | "multipleRecordLinks"
    | "checkbox"
    | "url"
    | "email"
    | "phoneNumber"
    | "formula"
    | "rollup"
    | "lookup"
    | "multipleLookupValues"
    | "count"
    | "autoNumber"
    | "barcode"
    | "button"
    | "createdBy"
    | "lastModifiedBy"
    | "externalSyncSource"
    | "aiText";
  name: string;
  description?: string;
  options?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
